### ISSUE TITLE
zap version issue in ssv5

### ISSUE THREAD

**Issue by KEEPHEADU** [SiliconLabs/matter_extension#3]
Failed to create new Configurable Project (SLCP)!
Multi-Exceptions available:
  Zap generation error: Error: C:\Users\Administrator\SimplicityStudio\v5_workspace\MatterLightOverThread_6\config\common\lighting-thread-app.zap requires feature level 99, we only have 98. Please upgrade your zap!

![image](https://github.com/SiliconLabs/matter_extension/assets/115463286/7dd38d3a-fb1d-4d54-a23d-17bddbe38760)

gsdk version: 4.3.2
matter_extension version: 2.2.0-rc2

It worked when I was using 2.1.1, but 2.1.1 didn't have the ICD cluster I wanted.

**Comment by Silabs-Hieu** [comment]
Can you go with me to the Matter community? https://community.silabs.com/s/question/0D5Vm000000YTxkKAG/how-to-use-matter-icd-cluster-on-ssv5

**Comment by KEEPHEADU** [comment]
OK
